"$schema" = "./node_modules/wrangler/config-schema.json"
name = "cloud-mail-docs"
compatibility_date = "2025-06-04"
main = "./worker/index.ts"

[assets]
directory = "./docs/.vitepress/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"